config/routes.rb
Rails.application.routes.draw do
  resources :leads

end

app/models/lead.rb
class Lead < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/leads_controller.rb
class LeadsController < ApplicationController
  # protect_from_forgery with: :null_session
  skip_before_filter :verify_authenticity_token

  before_action :set_lead, only: [:show, :edit, :update, :destroy]

  # GET /leads
  # GET /leads.json
  def index
    @leads = Lead.all
  end

  # GET /leads/1
  # GET /leads/1.json
  def show
  end

  # GET /leads/new
  def new
    @lead = Lead.new
  end

  # GET /leads/1/edit
  def edit
  end

  # POST /leads
  # POST /leads.json
  def create
    # byebug
    @lead = Lead.new(lead_params)

    if @lead.save
      ContactMailer.new_lead(@lead).deliver_now
      render json: {status: 'ok'}, status: :ok
      # format.html { redirect_to @lead, notice: 'Lead was successfully created.' }
      # format.json { render :show, status: :created, location: @lead }
      # format.js { render "ok", status: :ok }
    else
      render json: @lead.errors, status: :unprocessable_entity
      # format.html { render :new }
      # format.json { render json: @lead.errors, status: :unprocessable_entity }
      # format.js { render status: :unprocessable_entity }
    end
  end

  # PATCH/PUT /leads/1
  # PATCH/PUT /leads/1.json
  def update
    respond_to do |format|
      if @lead.update(lead_params)
        format.html { redirect_to @lead, notice: 'Lead was successfully updated.' }
        format.json { render :show, status: :ok, location: @lead }
      else
        format.html { render :edit }
        format.json { render json: @lead.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /leads/1
  # DELETE /leads/1.json
  def destroy
    @lead.destroy
    respond_to do |format|
      format.html { redirect_to leads_url, notice: 'Lead was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_lead
      @lead = Lead.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def lead_params
      params.require(:lead).permit(:email, :zone, :phone, :comment, :name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/leads_helper.rb
module LeadsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Coworkear</title>
  <meta name="robots" content="noindex">
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/leads/_form.html.erb
<%= form_for(@lead) do |f| %>
  <% if @lead.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@lead.errors.count, "error") %> prohibited this lead from being saved:</h2>

      <ul>
      <% @lead.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :email %><br>
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :zone %><br>
    <%= f.text_field :zone %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/leads/edit.html.erb
<h1>Editing Lead</h1>

<%= render 'form' %>

<%= link_to 'Show', @lead %> |
<%= link_to 'Back', leads_path %>

app/views/leads/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Leads</h1>

<table>
  <thead>
    <tr>
      <th>Email</th>
      <th>Name</th>
      <th>Zone</th>
      <th>Phone</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @leads.each do |lead| %>
      <tr>
        <td><%= lead.email %></td>
        <td><%= lead.name %></td>
        <td><%= lead.zone %></td>
        <td><%= lead.phone %></td>
        <td><%= lead.comment %></td>
        <td><%= link_to 'Show', lead %></td>
        <td><%= link_to 'Edit', edit_lead_path(lead) %></td>
        <td><%= link_to 'Destroy', lead, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Lead', new_lead_path %>

app/views/leads/new.html.erb
<h1>New Lead</h1>

<%= render 'form' %>

<%= link_to 'Back', leads_path %>

app/views/leads/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @lead.email %>
</p>

<p>
  <strong>Zone:</strong>
  <%= @lead.zone %>
</p>

<%= link_to 'Edit', edit_lead_path(@lead) %> |
<%= link_to 'Back', leads_path %>